/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  mySidebar: [
    {
      type: 'category',
      label: "VerifiedX Introduction",
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'introduction'
        },
      ]
    },
    // {
    //   type: 'category',
    //   label: "GUI",
    //   collapsed: false,
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'GUI'
    //     },
    //   ]
    // },
    {
      type: 'category',
      label: "Core CLI",
      collapsed: false,

      items: [
        {
          type: 'autogenerated',
          dirName: 'core'
        },
      ]
    },
    {
      type: 'category',
      label: "Switchblade (GUI)",
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'gui'
        },
      ]
    },
    {
      type: 'category',
      label: "Integrations",
      collapsed: false,

      items: [
        {
          type: 'autogenerated',
          dirName: 'integration'
        },
      ]
    },
    {
      type: 'category',
      label: "Tutorials",
      collapsed: false,

      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials'
        },
      ]
    },
    {
      type: 'category',
      label: "Documents",
      collapsed: false,

      items: [
        {
          type: 'autogenerated',
          dirName: 'documents'
        },
      ]
    },

    {
      type: 'category',
      label: "Network Assets",
      collapsed: false,

      items: [
        {
          type: 'autogenerated',
          dirName: 'network-assets'
        },
      ]
    }



  ]

};

module.exports = sidebars;
