/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  mySidebar: [
    {
      type: 'category',
      label: "ReserveBlock Introduction",
      collapsed: false,
      items: [ 
        {
        type: 'autogenerated',
        dirName: 'introduction'
        },
      ]
    },
    {
      type: 'category',
      label: "GUI",
      collapsed: false,
      items: [ 
        {
        type: 'autogenerated',
        dirName: 'GUI'
        },
      ]
    },
    {
      type: 'category',
      label: "CLI",
      collapsed: false,

      items: [ 
        {
        type: 'autogenerated',
        dirName: 'CLI'
        },
      ]
    },
    {
      type: 'category',
      label: "Integration",
      collapsed: false,

      items: [ 
        {
        type: 'autogenerated',
        dirName: 'integration'
        },
      ]
    },
    {
      type: 'category',
      label: "FAQs",
      collapsed: false,

      items: [ 
        {
        type: 'autogenerated',
        dirName: 'FAQs'
        },
      ]
    },
    {
      type: 'category',
      label: "Whitepaper Documents",
      collapsed: false,

      items: [ 
        {
        type: 'autogenerated',
        dirName: 'documents'
        },
      ]
    },
    {
      type: 'category',
      label: "Network",
      collapsed: false,

      items: [ 
        {
        type: 'autogenerated',
        dirName: 'network'
        },
      ]
    }
    
   
    
  ]
 
};

module.exports = sidebars;
